### ISSUE TITLE
能否再集成一下WooBox对电量与性能的优化？

### ISSUE THREAD

**Issue by PHCSJC** [HChenX/AppRetentionHook#1]
强化一下自带的墓碑，谢谢！

**Comment by HChenX** [comment]
不会加入强化小米墓碑的功能，专业的事交给专业的人。
关于电量和性能的kill方法已经Hook。

**Comment by PHCSJC** [comment]
3.7版本夜间不杀后台了，太牛了
大佬能不能再把音量键解冻和充电解冻再hook上呢？那就完美了，可以参考smillet这个来实现

**Comment by HChenX** [comment]
> 3.7版本夜间不杀后台了，太牛了 大佬能不能再把音量键解冻和充电解冻再hook上呢？那就完美了，可以参考smillet这个来实现

不会Hook和墓碑相关的东西
